# Generated by Django 6.1.1 on 2026-09-19 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_id', models.CharField(max_length=20, unique=True)),
                ('road_id', models.CharField(max_length=50)),
                ('road_name', models.CharField(max_length=200)),
                ('issue', models.CharField(max_length=255)),
                ('severity', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFICATION', 'Awaiting Verification'), ('CLOSED', 'Closed')], default='PENDING', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('assigned_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='contractors.contractor')),
            ],
        ),
    ]
