# Generated by Django 6.1.1 on 2026-09-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='is_delayed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='repeat_defect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='verification_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
