# Generated by Django 6.1.1 on 2026-09-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_id', models.CharField(max_length=50, unique=True)),
                ('road_name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('health_score', models.PositiveIntegerField(default=100)),
                ('risk_level', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('maintenance_priority', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('defect_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
