# Generated by Django 6.1.1 on 2026-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LifecycleEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_id', models.CharField(max_length=50)),
                ('road_name', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('CONSTRUCTION', 'Construction'), ('INSPECTION', 'Inspection'), ('DEFECT', 'Defect Detected'), ('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('VERIFICATION', 'Verification'), ('REINSPECTION', 'Re-inspection')], max_length=30)),
                ('description', models.TextField()),
                ('event_date', models.DateTimeField()),
                ('performed_by', models.CharField(blank=True, max_length=150)),
                ('reference_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
