# Generated by Django 6.1.1 on 2026-09-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractor_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('completed_projects', models.PositiveIntegerField(default=0)),
                ('delayed_projects', models.PositiveIntegerField(default=0)),
                ('repeat_defects', models.PositiveIntegerField(default=0)),
                ('average_repair_time', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('performance_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
